kind: ConfigMap
apiVersion: v1
metadata:
  name: jboss-cli
data:
  extensions.cli: |-
    embed-server --std-out=echo --server-config=standalone-openshift.xml
    :whoami
    quit
  postconfigure.sh: |-
    #!/usr/bin/env bash
    set -x
    echo "============================================="
    echo "Executing postconfigure.sh (extensions.cli)"
    echo "============================================="
    $JBOSS_HOME/bin/jboss-cli.sh --file=$JBOSS_HOME/extensions/extensions.cli